In [1]:
import numpy as np
import matplotlib.pyplot as plt
import sklearn.datasets as datasets
import sklearn.model_selection as model_selection

In [2]:
#O algoritmo KNN (k-Nearest Neighbors) é um algoritmo de aprendizado de máquina que classifica ou faz previsões com base na proximidade dos vizinhos mais próximos. Ele armazena um conjunto de pontos de treinamento com seus rótulos correspondentes.

#Implementando o KNN usando numpy

class KNN:
    #Definindo numeros de vizinhos e elementos de treinamento
    def __init__(self, k, X_train, y_train):
        self.k = k 
        self.X_train = X_train
        self.y_train = y_train
    #Calcular a distância euclidiana
    def distancia(self, n1, n2):
        distance = np.linalg.norm(n1-n2)
        return distance
    
    #Retornar os K vizinhos mais próximos de value
    def get_neighbors(self, value):
        distances = []
        for x in self.X_train:
            distances.append(self.distancia(value,x))
        distances = np.asarray(distances)
        indices = np.argpartition(distances, self.k)
        k_first = indices[:self.k]
        return k_first
    
    #Realizando a previsão de um elemento dado o conjunto de treinamento
    def predict(self, value):
        knn_indices = self.get_neighbors(value)
        knn_labels=[]
        for i in knn_indices:
            knn_labels.append(self.y_train[i])
        occurrences = np.bincount(knn_labels)
        node=np.argmax(occurrences)
        return node
    
    #Retornar a acurácia
    def accuracy(self, y_test, predictions):
        correct = y_test == predictions
        acc = (np.sum(correct) / y_test.shape[0])*100
        return acc

In [3]:
#Testando classe acima
X,y = datasets.load_iris(return_X_y=True) #Carregando o dataset iris
X_train, X_test, y_train, y_test = model_selection.train_test_split(X,y,test_size=0.3, random_state=13) #Dividindo o dataset em treinamento e teste
knn = KNN(10, X_train, y_train) #Instanciando o knn

preds=[] #Variável que vai armazenar o resultado da previsão

for x in X_test:
    preds.append(knn.predict(x)) # Realizando a previsão em cada elemento de X_test e guardando em preds

acc = knn.accuracy(y_test, preds) #Comparando resultados
print(f"Acuracia de {acc}% (Classe implementada por mim)")

#Comparando com o modelo do sklearn
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics
knnSKL = KNeighborsClassifier(n_neighbors=10)
knnSKL.fit(X_train, y_train)
y_pred = knnSKL.predict(X_test)
acc = metrics.accuracy_score(y_test, y_pred)*100
print(f"Acuracia de {acc}% (Utilizando SKLEARN)")





Acuracia de 93.33333333333333% (Classe implementada por mim)
Acuracia de 93.33333333333333% (Utilizando SKLEARN)


In [4]:
import pandas as pd
vinhos_ds  = pd.read_csv("./winequality.csv") #Lendo o arquivo
#Normalizando os dados do ds
print(vinhos_ds.columns)
for c in vinhos_ds.columns:
    vinhos_ds[c] = (vinhos_ds [c] - min(vinhos_ds[c]))/(max(vinhos_ds[c]) -min(vinhos_ds[c]))
print(vinhos_ds.isnull().sum()) #Vendo há valores nulos
print(vinhos_ds.info()) #Vendo se todas as variáveis são numéricas

#Definindo X e Y
y = vinhos_ds['wine_is_red']
X = vinhos_ds.drop('wine_is_red', axis=1)

#Separando em treinamento e teste
X_train, X_test, y_train, y_test = model_selection.train_test_split(X,y,test_size=0.2, random_state=13)

#Aplicando o KNN para a classificação binária
knnSKL = KNeighborsClassifier(n_neighbors=10)
knnSKL.fit(X_train, y_train)
y_pred = knnSKL.predict(X_test)

#Vendo a acurácia do modelo
acc = metrics.accuracy_score(y_test, y_pred)*100
print(f"Acuracia de {acc}%")
from sklearn.metrics import confusion_matrix, classification_report
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))



Index(['Unnamed: 0', 'fixed acidity', 'volatile acidity', 'citric acid',
       'residual sugar', 'chlorides', 'free sulfur dioxide',
       'total sulfur dioxide', 'density', 'pH', 'sulphates', 'alcohol',
       'quality', 'wine_is_red'],
      dtype='object')
Unnamed: 0              0
fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
wine_is_red             0
dtype: int64
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6497 entries, 0 to 6496
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   Unnamed: 0            6497 non-null   float64
 1   fixed acidity         6497 non-null   float64
 2   volatile acidity      6497 non-null   float64

In [5]:
#Comparando os resultados no caso dos dados não serem normalizados
import pandas as pd
vinhos_ds  = pd.read_csv("./winequality.csv") #Lendo o arquivo

#Definindo X e Y
y = vinhos_ds['wine_is_red']
X = vinhos_ds.drop('wine_is_red', axis=1)

#Separando em treinamento e teste
X_train, X_test, y_train, y_test = model_selection.train_test_split(X,y,test_size=0.2, random_state=13)

#Aplicando o KNN para a classificação binária
knnSKL = KNeighborsClassifier(n_neighbors=10)
knnSKL.fit(X_train, y_train)
y_pred = knnSKL.predict(X_test)

#Vendo a acurácia do modelo
acc = metrics.accuracy_score(y_test, y_pred)*100
print(f"Acuracia de {acc}%") #Acurácia relativamente menor quando os dados não estão normalizados

print("Quando os dados foram normalizados o modelo apresentou uma acurácia entre 98-99% e quando os dados não foram normalizado a acurácia caiu para 90-93%")
from sklearn.metrics import confusion_matrix, classification_report
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

Acuracia de 92.38461538461539%
Quando os dados foram normalizados o modelo apresentou uma acurácia entre 98-99% e quando os dados não foram normalizado a acurácia caiu para 90-93%
              precision    recall  f1-score   support

           0       0.93      0.97      0.95       974
           1       0.90      0.78      0.84       326

    accuracy                           0.92      1300
   macro avg       0.92      0.88      0.89      1300
weighted avg       0.92      0.92      0.92      1300

[[946  28]
 [ 71 255]]


In [6]:
#Verificando a classificação binária usando uma regressão logística
from sklearn.linear_model import LogisticRegression

vinhos_ds  = pd.read_csv("./winequality.csv") #Lendo o arquivo

#Definindo X e Y
y = vinhos_ds['wine_is_red']
X = vinhos_ds.drop('wine_is_red', axis=1)

#Separando em treinamento e teste
X_train, X_test, y_train, y_test = model_selection.train_test_split(X,y,test_size=0.2, random_state=13)

#Aplicando a regressão logística
model = LogisticRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

#Verificando a acurácia quando se aplica a regressão logística e o dataset não está normalizado
acc = metrics.accuracy_score(y_test, y_pred)*100
print(f"Acuracia de {acc}%")


Acuracia de 94.0%


c:\Users\vh_co\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [7]:
#Verificando a classificação binária usando uma regressão logística em um dataset normalizado
from sklearn.linear_model import LogisticRegression

vinhos_ds  = pd.read_csv("./winequality.csv") #Lendo o arquivo
for c in vinhos_ds.columns:
    vinhos_ds[c] = (vinhos_ds [c] - min(vinhos_ds[c]))/(max(vinhos_ds[c]) -min(vinhos_ds[c]))

#Definindo X e Y
y = vinhos_ds['wine_is_red']
X = vinhos_ds.drop('wine_is_red', axis=1)

#Separando em treinamento e teste
X_train, X_test, y_train, y_test = model_selection.train_test_split(X,y,test_size=0.2, random_state=13)

#Aplicando a regressão logística
model = LogisticRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

#Verificando a acurácia quando se aplica a regressão logística e o dataset não está normalizado
acc = metrics.accuracy_score(y_test, y_pred)*100
print(f"Acuracia de {acc}%")
print(classification_report(y_test, y_pred))

print("Novamente a acurácia foi maior nos modelos que recebiam os dados normalizados")
print("Utilizando a regressão logística obtive uma acurácia maior do que com o KNN")


Acuracia de 98.92307692307692%
              precision    recall  f1-score   support

         0.0       0.99      1.00      0.99       974
         1.0       0.99      0.97      0.98       326

    accuracy                           0.99      1300
   macro avg       0.99      0.98      0.99      1300
weighted avg       0.99      0.99      0.99      1300

Novamente a acurácia foi maior nos modelos que recebiam os dados normalizados
Utilizando a regressão logística obtive uma acurácia maior do que com o KNN


In [8]:
vinhos_ds  = pd.read_csv("./winequality.csv") #Lendo o arquivo
print(f"Vinhos tintos = {vinhos_ds['wine_is_red'].sum()} / Vinhos brancos = {len(vinhos_ds['wine_is_red']) - vinhos_ds['wine_is_red'].sum()}")
#Dataset desbalanceado
#Aplicando oversample
white = vinhos_ds[vinhos_ds['wine_is_red'] == 0 ]
red = vinhos_ds[vinhos_ds['wine_is_red'] == 1 ]
print(white.shape)
print(red.shape)
df_red_over = red.sample(4898, replace=True) #Duplicando dados
print(df_red_over.shape)
new_vinhos_ds = pd.concat([white, df_red_over], axis=0)
#Verificando o novo dataframe
print(f"Vinhos tintos = {new_vinhos_ds['wine_is_red'].sum()} / Vinhos brancos = {len(new_vinhos_ds['wine_is_red']) - new_vinhos_ds['wine_is_red'].sum()}")
#Aplicando a regressão logística no novo data frame
for c in new_vinhos_ds.columns:
    new_vinhos_ds[c] = (new_vinhos_ds [c] - min(new_vinhos_ds[c]))/(max(new_vinhos_ds[c]) -min(new_vinhos_ds[c]))

#Definindo X e Y
y = new_vinhos_ds['wine_is_red']
X = new_vinhos_ds.drop('wine_is_red', axis=1)

#Separando em treinamento e teste
X_train, X_test, y_train, y_test = model_selection.train_test_split(X,y,test_size=0.2, random_state=13)

#Aplicando a regressão logística
model = LogisticRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

#Verificando resultados do modelo
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))


Vinhos tintos = 1599 / Vinhos brancos = 4898
(4898, 14)
(1599, 14)
(4898, 14)
Vinhos tintos = 4898 / Vinhos brancos = 4898


              precision    recall  f1-score   support

         0.0       0.99      0.98      0.99       969
         1.0       0.98      0.99      0.99       991

    accuracy                           0.99      1960
   macro avg       0.99      0.99      0.99      1960
weighted avg       0.99      0.99      0.99      1960

[[950  19]
 [  7 984]]


In [9]:
vinhos_ds  = pd.read_csv("./winequality.csv") #Lendo o arquivo
white = vinhos_ds[vinhos_ds['wine_is_red'] == 0 ]
red = vinhos_ds[vinhos_ds['wine_is_red'] == 1 ]
df_white_under = white.sample(1599, replace=True) #Duplicando dados
print(df_white_under.shape)
new_vinhos_ds = pd.concat([red, df_white_under], axis=0)
#Verificando o novo dataframe
print(f"Vinhos tintos = {new_vinhos_ds['wine_is_red'].sum()} / Vinhos brancos = {len(new_vinhos_ds['wine_is_red']) - new_vinhos_ds['wine_is_red'].sum()}")
#Aplicando a regressão logística no novo data frame
for c in new_vinhos_ds.columns:
    new_vinhos_ds[c] = (new_vinhos_ds [c] - min(new_vinhos_ds[c]))/(max(new_vinhos_ds[c]) -min(new_vinhos_ds[c]))

#Definindo X e Y
y = new_vinhos_ds['wine_is_red']
X = new_vinhos_ds.drop('wine_is_red', axis=1)

#Separando em treinamento e teste
X_train, X_test, y_train, y_test = model_selection.train_test_split(X,y,test_size=0.2, random_state=13)

#Aplicando a regressão logística
model = LogisticRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

#Verificando resultados do modelo
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

(1599, 14)
Vinhos tintos = 1599 / Vinhos brancos = 1599
              precision    recall  f1-score   support

         0.0       0.98      0.99      0.99       312
         1.0       0.99      0.98      0.99       328

    accuracy                           0.99       640
   macro avg       0.99      0.99      0.99       640
weighted avg       0.99      0.99      0.99       640

[[310   2]
 [  5 323]]


In [10]:
from sklearn.ensemble import RandomForestClassifier
vinhos_ds  = pd.read_csv("./winequality.csv") #Lendo o arquivo

vinhos_ds = vinhos_ds.drop('Unnamed: 0', axis=1)
print(vinhos_ds.columns) #Verificando as colunas
X = vinhos_ds.drop('quality', axis=1)
y = vinhos_ds['quality']
#Dividinho em treinamento e teste
X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y, test_size=0.2, random_state=42)

#Aplicando no modelo
rf_model = RandomForestClassifier()
rf_model = RandomForestClassifier()
rf_model.fit(X_train, y_train)
y_pred = rf_model.predict(X_test)

#Verificando os resultados
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))


Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality', 'wine_is_red'],
      dtype='object')


c:\Users\vh_co\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:1151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


              precision    recall  f1-score   support

           3       0.00      0.00      0.00         3
           4       0.62      0.11      0.18        47
           5       0.71      0.74      0.73       407
           6       0.68      0.78      0.73       592
           7       0.69      0.54      0.61       215
           8       0.80      0.47      0.59        34
           9       0.00      0.00      0.00         2

    accuracy                           0.69      1300
   macro avg       0.50      0.38      0.41      1300
weighted avg       0.69      0.69      0.68      1300

[[  0   0   3   0   0   0   0]
 [  1   5  23  18   0   0   0]
 [  0   3 302  99   3   0   0]
 [  0   0  92 461  39   0   0]
 [  0   0   5  89 117   4   0]
 [  0   0   0   9   9  16   0]
 [  0   0   0   1   1   0   0]]


c:\Users\vh_co\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\vh_co\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\vh_co\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average,

In [11]:
print(vinhos_ds.quality.value_counts())
#É possível observar que os dados não estão balanceados
q6 = vinhos_ds[vinhos_ds['quality'] == 6 ]
q5 = vinhos_ds[vinhos_ds['quality'] == 5 ]
q7 = vinhos_ds[vinhos_ds['quality'] == 7 ]
q4 = vinhos_ds[vinhos_ds['quality'] == 4 ]
q8 = vinhos_ds[vinhos_ds['quality'] == 8 ]
q3 = vinhos_ds[vinhos_ds['quality'] == 3 ]
q9 = vinhos_ds[vinhos_ds['quality'] == 9 ]

q5_over = q5.sample(2836, replace=True)
q7_over = q7.sample(2836, replace=True)
q4_over = q4.sample(2836, replace=True)
q8_over = q8.sample(2836, replace=True)
q3_over = q3.sample(2836, replace=True)
q9_over = q9.sample(2836, replace=True)

new_vinhos_ds = pd.concat([q6,q5_over, q7_over, q4_over,q8_over,q3_over,q9_over], axis=0)

#Dados agora balanceados
print(new_vinhos_ds.quality.value_counts())

X = new_vinhos_ds.drop('quality', axis=1)
y = new_vinhos_ds['quality']
#Dividinho em treinamento e teste
X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y, test_size=0.2, random_state=42)

#Aplicando no modelo
rf_model = RandomForestClassifier()
rf_model = RandomForestClassifier()
rf_model.fit(X_train, y_train)
y_pred = rf_model.predict(X_test)

#Verificando os resultados
print(classification_report(y_test, y_pred))
print("É possível observar que todas as métricas de avalização melhoraram após a aplicação do oversampling")



c:\Users\vh_co\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:1151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


quality
6    2836
5    2138
7    1079
4     216
8     193
3      30
9       5
Name: count, dtype: int64
quality
6    2836
5    2836
7    2836
4    2836
8    2836
3    2836
9    2836
Name: count, dtype: int64
              precision    recall  f1-score   support

           3       1.00      1.00      1.00       598
           4       0.99      1.00      0.99       574
           5       0.87      0.89      0.88       574
           6       0.84      0.77      0.80       544
           7       0.91      0.95      0.93       578
           8       1.00      1.00      1.00       576
           9       1.00      1.00      1.00       527

    accuracy                           0.94      3971
   macro avg       0.94      0.94      0.94      3971
weighted avg       0.94      0.94      0.94      3971

É possível observar que todas as métricas de avalização melhoraram após a aplicação do oversampling


In [12]:
# Obtendo as características mais importantes do modelo
feature_importance = rf_model.feature_importances_

# Criando um DataFrame para visualizar a importância das características
feature_importance_df = pd.DataFrame({'Característica': X.columns, 'Importância': feature_importance})

# Ordenando as características pela importância em ordem decrescente
feature_importance_df = feature_importance_df.sort_values(by='Importância', ascending=False)

print(feature_importance_df)

          Característica  Importância
10               alcohol     0.108354
7                density     0.108352
4              chlorides     0.104334
5    free sulfur dioxide     0.099376
0          fixed acidity     0.095856
1       volatile acidity     0.092796
6   total sulfur dioxide     0.083805
8                     pH     0.083476
3         residual sugar     0.078975
2            citric acid     0.072358
9              sulphates     0.067316
11           wine_is_red     0.005002
